import { useState, useEffect, useCallback } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import {
  Plus,
  Video,
  Trash2,
  Calendar,
  Sparkles,
  Play,
  FileCheck,
  Layers,
  AlertCircle,
  Zap,
} from 'lucide-react';
import toast from 'react-hot-toast';
import interviewService from '../services/interview.service.js';
import useUsageQuota from '../hooks/useUsageQuota.js';
import UpgradeModal from '../components/pricing/UpgradeModal.jsx';
import {
  EXPERIENCE_LEVELS,
  DIFFICULTY_LEVELS,
  INTERVIEW_TYPES,
  QUESTION_COUNTS,
} from '../utils/constants.js';
import Button from '../components/common/Button.jsx';
import Badge from '../components/common/Badge.jsx';
import Modal from '../components/common/Modal.jsx';
import EmptyState from '../components/common/EmptyState.jsx';

const MockInterviewsPage = () => {
  const [interviews, setInterviews] = useState([]);
  const [loading, setLoading] = useState(true);
  const [openDialog, setOpenDialog] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [upgradeModalOpen, setUpgradeModalOpen] = useState(false);
  const navigate = useNavigate();

  const { plan, isPaid, updatePlan, refreshUsage, getQuotaFor } = useUsageQuota();
  const quota = getQuotaFor('interviewsGenerated');

  const [form, setForm] = useState({
    jobRole: '',
    jobDescription: '',
    experienceLevel: 'fresher',
    techStack: '',
    interviewType: 'technical',
    difficulty: 'medium',
    numberOfQuestions: 5,
  });

  const fetchInterviews = useCallback(async () => {
    try {
      setLoading(true);
      const res = await interviewService.getAll();
      setInterviews(res.data || []);
    } catch (err) {
      toast.error(err.message || 'Failed to fetch interviews');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchInterviews();
  }, [fetchInterviews]);

  const handleOpenCreateModal = () => {
    if (!quota.isUnlimited && quota.isExceeded) {
      toast.error('Free plan limit reached (5/5 interviews). Upgrade to Paid for unlimited sessions.');
      setUpgradeModalOpen(true);
      return;
    }
    setOpenDialog(true);
  };

  const handleCreate = async (e) => {
    e.preventDefault();
    if (!quota.isUnlimited && quota.isExceeded) {
      toast.error('Free plan limit reached (5/5 interviews). Upgrade to Paid for unlimited sessions.');
      setUpgradeModalOpen(true);
      return;
    }
    if (!form.jobRole.trim()) {
      return toast.error('Please enter a job role');
    }
    if (!form.jobDescription.trim()) {
      return toast.error('Please provide job details or description');
    }

    setSubmitting(true);
    try {
      const res = await interviewService.create(form);
      toast.success('Interview questions generated by Gemini AI!');
      setOpenDialog(false);
      refreshUsage();
      navigate(`/dashboard/mocks/${res.data._id}`);
    } catch (err) {
      const errMsg =
        err.response?.data?.message || err.message || 'Failed to generate interview questions';
      toast.error(errMsg);
      if (err.response?.status === 429 || errMsg.includes('limit reached')) {
        setUpgradeModalOpen(true);
      }
    } finally {
      setSubmitting(false);
    }
  };

  const handleDelete = async (id) => {
    if (!window.confirm('Are you sure you want to delete this interview?')) return;
    try {
      await interviewService.delete(id);
      setInterviews((prev) => prev.filter((i) => i._id !== id));
      toast.success('Interview deleted');
    } catch (err) {
      toast.error(err.message || 'Failed to delete interview');
    }
  };

  const getScoreBadge = (score) => {
    if (score === null || score === undefined) {
      return (
        <Badge variant="amber" size="sm">
          Pending
        </Badge>
      );
    }
    if (score >= 8) {
      return (
        <Badge variant="emerald" size="sm" dot>
          {score}/10 Excellent
        </Badge>
      );
    }
    if (score >= 6) {
      return (
        <Badge variant="indigo" size="sm" dot>
          {score}/10 Good
        </Badge>
      );
    }
    return (
      <Badge variant="rose" size="sm" dot>
        {score}/10 Needs Practice
      </Badge>
    );
  };

  return (
    <div className="space-y-8 animate-fadeIn">
      {/* Page Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl sm:text-3xl font-extrabold font-heading text-white">
            AI Mock Interviews
          </h1>
          <p className="text-sm text-slate-400 mt-1">
            Simulate realistic technical and behavioral interviews with Gemini AI voice & video.
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-3">
          {quota.isUnlimited ? (
            <Badge variant="indigo" size="md" dot>
              <Sparkles className="h-3 w-3 mr-1 inline text-yellow-300" />
              Unlimited Pro Tier
            </Badge>
          ) : (
            <div className="flex items-center gap-2">
              <Badge
                variant={quota.isExceeded ? 'rose' : 'amber'}
                size="md"
                dot={quota.isExceeded}
              >
                {quota.current} / 5 Free Sessions
              </Badge>
              <Button
                size="xs"
                variant="primary"
                onClick={() => setUpgradeModalOpen(true)}
                icon={Zap}
              >
                Upgrade
              </Button>
            </div>
          )}

          <Button
            onClick={handleOpenCreateModal}
            variant="primary"
            size="md"
            icon={Plus}
          >
            New Interview
          </Button>
        </div>
      </div>

      {/* Quota Exceeded Alert Banner */}
      {!quota.isUnlimited && quota.isExceeded && (
        <div className="glass-panel border-2 border-rose-500/40 bg-gradient-to-r from-rose-950/40 via-slate-900/80 to-slate-950/80 rounded-2xl p-5 sm:p-6 flex flex-col sm:flex-row items-center justify-between gap-4 shadow-lg shadow-rose-950/20">
          <div className="flex items-center gap-4 text-center sm:text-left">
            <div className="w-12 h-12 rounded-xl bg-rose-500/20 text-rose-400 border border-rose-500/30 flex items-center justify-center shrink-0">
              <AlertCircle className="h-6 w-6" />
            </div>
            <div>
              <h4 className="text-base font-bold text-white font-heading">
                Free Plan Limit Reached (5 of 5 Used)
              </h4>
              <p className="text-xs sm:text-sm text-slate-300 mt-1">
                You've completed all 5 free mock interviews. Upgrade to Unlimited Pro to continue practicing without limits.
              </p>
            </div>
          </div>
          <Button
            variant="primary"
            size="sm"
            onClick={() => setUpgradeModalOpen(true)}
            icon={Sparkles}
            className="w-full sm:w-auto shrink-0"
          >
            Unlock Unlimited Access
          </Button>
        </div>
      )}

      {/* New Interview Action Banner */}
      <div
        onClick={handleOpenCreateModal}
        className="glass-panel-interactive border-dashed border-indigo-500/30 rounded-2xl p-6 sm:p-8 cursor-pointer flex flex-col sm:flex-row items-center justify-between gap-4 group"
      >
        <div className="flex items-center gap-4 text-center sm:text-left">
          <div className="w-12 h-12 rounded-xl bg-gradient-to-tr from-indigo-600 to-purple-600 flex items-center justify-center text-white shadow-lg shadow-indigo-500/25 group-hover:scale-110 transition-transform shrink-0">
            <Sparkles className="h-6 w-6" />
          </div>
          <div>
            <h3 className="text-lg font-bold text-white font-heading">
              Ready to test your skills?
            </h3>
            <p className="text-xs sm:text-sm text-slate-400 mt-0.5">
              Generate tailored interview questions based on job description, tech stack, and role.
            </p>
          </div>
        </div>
        <Button variant="primary" size="sm" icon={Plus}>
          Start Practice
        </Button>
      </div>

      {/* Interview History List */}
      <div>
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-lg font-bold font-heading text-white flex items-center gap-2">
            <Layers className="h-4 w-4 text-indigo-400" />
            Previous Sessions
          </h2>
          <span className="text-xs text-slate-400">
            {interviews.length} {interviews.length === 1 ? 'session' : 'sessions'}
          </span>
        </div>

        {loading ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
            {[1, 2, 3].map((n) => (
              <div
                key={n}
                className="glass-panel rounded-2xl p-6 h-48 animate-pulse flex flex-col justify-between"
              >
                <div className="space-y-2">
                  <div className="h-5 bg-slate-800 rounded w-2/3" />
                  <div className="h-4 bg-slate-800/60 rounded w-1/2" />
                </div>
                <div className="h-8 bg-slate-800 rounded w-full" />
              </div>
            ))}
          </div>
        ) : interviews.length === 0 ? (
          <EmptyState
            icon={Video}
            title="No Interviews Created Yet"
            description="Create your first mock interview to practice answering questions with audio and camera feedback."
            actionLabel="Generate Interview"
            onAction={() => setOpenDialog(true)}
          />
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
            {interviews.map((item) => (
              <div
                key={item._id}
                className="glass-panel-interactive rounded-2xl p-6 flex flex-col justify-between"
              >
                <div>
                  <div className="flex items-start justify-between gap-2 mb-3">
                    <span className="text-xs font-mono uppercase tracking-wider text-indigo-400">
                      {item.interviewType || 'Technical'}
                    </span>
                    {getScoreBadge(item.overallScore)}
                  </div>

                  <h3 className="text-lg font-bold text-white font-heading line-clamp-1 mb-1">
                    {item.jobRole}
                  </h3>

                  <p className="text-xs text-slate-400 line-clamp-2 mb-4">
                    {item.jobDescription}
                  </p>

                  <div className="flex flex-wrap items-center gap-2 text-xs text-slate-400 mb-5">
                    <Badge variant="slate" size="sm">
                      {item.experienceLevel}
                    </Badge>
                    <Badge variant="purple" size="sm">
                      {item.questions?.length || 5} Questions
                    </Badge>
                    <span className="flex items-center gap-1 text-[11px] text-slate-500 ml-auto">
                      <Calendar className="h-3 w-3" />
                      {new Date(item.createdAt).toLocaleDateString()}
                    </span>
                  </div>
                </div>

                <div className="flex items-center gap-2 pt-3 border-t border-white/5">
                  <Button
                    onClick={() => navigate(`/dashboard/mocks/${item._id}`)}
                    variant={item.status === 'completed' ? 'secondary' : 'primary'}
                    size="sm"
                    className="flex-1"
                    icon={item.status === 'completed' ? FileCheck : Play}
                  >
                    {item.status === 'completed' ? 'Review Feedback' : 'Resume Interview'}
                  </Button>
                  <button
                    onClick={() => handleDelete(item._id)}
                    className="p-2 text-slate-400 hover:text-rose-400 hover:bg-rose-500/10 rounded-xl transition-colors cursor-pointer"
                    title="Delete session"
                  >
                    <Trash2 className="h-4 w-4" />
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Creation Modal */}
      <Modal
        isOpen={openDialog}
        onClose={() => setOpenDialog(false)}
        title="Configure New Mock Interview"
        description="Gemini AI will generate realistic, context-specific questions for your practice session."
        maxWidth="max-w-xl"
      >
        <form onSubmit={handleCreate} className="space-y-4">
          {/* Plan Quota Notice */}
          <div
            className={`p-3 rounded-xl border text-xs flex items-center justify-between ${
              quota.isUnlimited
                ? 'bg-indigo-500/10 border-indigo-500/30 text-indigo-300'
                : quota.isExceeded
                ? 'bg-rose-500/10 border-rose-500/30 text-rose-300'
                : 'bg-slate-800/60 border-slate-700/60 text-slate-300'
            }`}
          >
            <span className="flex items-center gap-1.5 font-medium">
              <Sparkles className="h-3.5 w-3.5 text-indigo-400" />
              Interview Quota:
            </span>
            <div className="flex items-center gap-2">
              <span className="font-bold">
                {quota.isUnlimited
                  ? 'Unlimited Mock Interviews'
                  : `${quota.remaining} of 5 free interviews left`}
              </span>
              {!quota.isUnlimited && (
                <button
                  type="button"
                  onClick={() => {
                    setOpenDialog(false);
                    setUpgradeModalOpen(true);
                  }}
                  className="text-[11px] text-indigo-400 hover:text-indigo-300 underline font-semibold cursor-pointer"
                >
                  Upgrade
                </button>
              )}
            </div>
          </div>
          <div>
            <label className="block text-xs font-semibold uppercase tracking-wider text-slate-300 mb-1.5">
              Target Job Role / Position *
            </label>
            <input
              type="text"
              required
              placeholder="e.g. Senior Full Stack Engineer, Frontend Specialist"
              value={form.jobRole}
              onChange={(e) => setForm({ ...form, jobRole: e.target.value })}
              className="w-full bg-slate-900/80 border border-slate-700/80 focus:border-indigo-500 rounded-xl p-3 text-sm text-white placeholder-slate-500 outline-none transition-colors"
            />
          </div>

          <div>
            <label className="block text-xs font-semibold uppercase tracking-wider text-slate-300 mb-1.5">
              Job Description / Responsibilities *
            </label>
            <textarea
              required
              rows={3}
              placeholder="Paste job description highlights or key skills needed for this role..."
              value={form.jobDescription}
              onChange={(e) => setForm({ ...form, jobDescription: e.target.value })}
              className="w-full bg-slate-900/80 border border-slate-700/80 focus:border-indigo-500 rounded-xl p-3 text-sm text-white placeholder-slate-500 outline-none transition-colors"
            />
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-slate-300 mb-1.5">
                Tech Stack (Optional)
              </label>
              <input
                type="text"
                placeholder="e.g. React, Node.js, AWS, Postgres"
                value={form.techStack}
                onChange={(e) => setForm({ ...form, techStack: e.target.value })}
                className="w-full bg-slate-900/80 border border-slate-700/80 focus:border-indigo-500 rounded-xl p-3 text-sm text-white placeholder-slate-500 outline-none transition-colors"
              />
            </div>

            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-slate-300 mb-1.5">
                Experience Level
              </label>
              <select
                value={form.experienceLevel}
                onChange={(e) => setForm({ ...form, experienceLevel: e.target.value })}
                className="w-full bg-slate-900/80 border border-slate-700/80 focus:border-indigo-500 rounded-xl p-3 text-sm text-white outline-none transition-colors"
              >
                {EXPERIENCE_LEVELS.map((exp) => (
                  <option key={exp.value} value={exp.value} className="bg-slate-900 text-white">
                    {exp.label}
                  </option>
                ))}
              </select>
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-slate-300 mb-1.5">
                Interview Type
              </label>
              <select
                value={form.interviewType}
                onChange={(e) => setForm({ ...form, interviewType: e.target.value })}
                className="w-full bg-slate-900/80 border border-slate-700/80 focus:border-indigo-500 rounded-xl p-3 text-sm text-white outline-none transition-colors"
              >
                {INTERVIEW_TYPES.map((t) => (
                  <option key={t.value} value={t.value} className="bg-slate-900 text-white">
                    {t.label}
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-slate-300 mb-1.5">
                Difficulty
              </label>
              <select
                value={form.difficulty}
                onChange={(e) => setForm({ ...form, difficulty: e.target.value })}
                className="w-full bg-slate-900/80 border border-slate-700/80 focus:border-indigo-500 rounded-xl p-3 text-sm text-white outline-none transition-colors"
              >
                {DIFFICULTY_LEVELS.map((d) => (
                  <option key={d.value} value={d.value} className="bg-slate-900 text-white">
                    {d.label}
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-slate-300 mb-1.5">
                Questions
              </label>
              <select
                value={form.numberOfQuestions}
                onChange={(e) =>
                  setForm({ ...form, numberOfQuestions: Number(e.target.value) })
                }
                className="w-full bg-slate-900/80 border border-slate-700/80 focus:border-indigo-500 rounded-xl p-3 text-sm text-white outline-none transition-colors"
              >
                {QUESTION_COUNTS.map((cnt) => (
                  <option key={cnt} value={cnt} className="bg-slate-900 text-white">
                    {cnt} Questions
                  </option>
                ))}
              </select>
            </div>
          </div>

          <div className="flex gap-3 pt-3">
            <Button
              type="button"
              variant="secondary"
              className="w-full"
              onClick={() => setOpenDialog(false)}
            >
              Cancel
            </Button>
            <Button
              type="submit"
              variant="primary"
              className="w-full"
              loading={submitting}
              icon={Sparkles}
            >
              Generate Questions
            </Button>
          </div>
        </form>
      </Modal>

      {/* Upgrade Modal */}
      <UpgradeModal
        isOpen={upgradeModalOpen}
        onClose={() => setUpgradeModalOpen(false)}
        onUpgradeSuccess={() => refreshUsage()}
        updatePlan={updatePlan}
      />
    </div>
  );
};

export default MockInterviewsPage;
